version: '3.3'
services:
  db:
    image: mysql:5.7
    restart: always
    command: mysqld --character-set-server=utf8 --collation-server=utf8_unicode_ci --init-connect='SET NAMES UTF8;' --innodb-flush-log-at-trx-commit=0
    container_name: todos-db
    environment:
      MYSQL_DATABASE: 'todos'
      MYSQL_USER: 'todos'
      MYSQL_PASSWORD: 'i0jsi7pf9c3w'
      MYSQL_ROOT_PASSWORD: 'i0jsi7pf9c3w'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - todos-db:/var/lib/mysql
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
# Names our volume
volumes:
  mpsales-db: